export const CREATE_CAMPUS = 'CREATE_CAMPUS';
export const UPDATE_CAMPUS = 'UPDATE_CAMPUS';
export const DELETE_CAMPUS = 'DELETE_CAMPUS';
export const SET_CAMPUSES = 'SET_CAMPUSES';

export const CREATE_STUDENT = 'CREATE_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const SET_STUDENTS = 'SET_STUDENTS';